### PR TITLE
Added Tuneder

### PR DESCRIPTION
**Pull request by adityasaravana**

### CODE REVIEW

**Comment by Divide-By-0** [comment]
Cool! Will accept once the demos available for users to try. Please email me a preferred payment method! I prefer venmo or ethereum but PayPal works.

**Comment by adityasaravana** [comment]
Thanks, Aayush! The Xcode project builds fine, and you should be able to install it on any iPhone with iOS 16. Do you mean an App Store release?

**Comment by Divide-By-0** [comment]
Yeah! Usually I only accept bounties with a deployed website, so I think the analogy here for apps would be a one click install download (can be a file download from a website or app store release, but preferably app store release).

**Comment by adityasaravana** [comment]
Sounds good, Aayush. Thanks!

**Comment by adityasaravana** [comment]
Hey Aayush,

I released it! Here’s the App Store link: https://apps.apple.com/us/app/tuneder-song-discovery/id6450867856?itsct=apps_box_badge&itscg=30200. I  didn’t add support for Spotify users yet, but it’ll work right out of the box with any Apple Music subscription, and they have a one-month free trial with no strings attached you can use to test Tuneder if you’re interested.

Regards, 
Aditya

**Comment by Divide-By-0** [comment]
Awesome, let me knownonce youve fixed the merge conflict and emailed me a payment method! Ethereum preferred, venmo good, PayPal ok.

**Comment by adityasaravana** [comment]
Done!

**Comment by Divide-By-0** [comment]
Sent, thanks! You should advertise on twitter, relevant subreddits, apple
music forums, and producthunt to get the word out there, this is awesome :)

**Comment by adityasaravana** [comment]
Thanks, Aayush!Sent from my iPhoneOn Jul 7, 2023, at 12:18 PM, Yush G ***@***.***> wrote:﻿
Sent, thanks! You should advertise on twitter, relevant subreddits, apple

music forums, and producthunt to get the word out there, this is awesome :)



On Fri, Jul 7, 2023, 3:04 PM Aditya Saravana ***@***.***>

wrote:



> Done!

>

**Pull request merged**
