### PR TITLE
404 to Archive Redirecter

### PR DESCRIPTION
**Pull request by DanzHD**
A greasemonkey/tampermonkey script to, when detecting a page that says "404" or "Not Found" on it, automatically redirect to that page in the Internet Archive.

Can be installed here https://greasyfork.org/en/scripts/484103-404pagerevival

### CODE REVIEW

**Comment by DanzHD** [comment]
@Divide-By-0 sorry, were there any issues that you wanted me to fix?

**Comment by Divide-By-0** [comment]
> @Divide-By-0 sorry, were there any issues that you wanted me to fix?

Hey sorry I haven't been as responsive. Just installed, will try out for a week. One quick nit is that the serif font is sort of ugly, and it should automatically check archive.org instead of asking me to click the button.

**Comment by DanzHD** [comment]
> > @Divide-By-0 sorry, were there any issues that you wanted me to fix?
> 
> Hey sorry I haven't been as responsive. Just installed, will try out for a week. One quick nit is that the serif font is sort of ugly, and it should automatically check archive.org instead of asking me to click the button first.
> 
> Also, https://login.live.com/login.srf seems to trigger this extension even though it's not a 404.

I can definitely change the font style and make it check archive.org on initial load but I don't think I can do anything else to prevent false positives due to the fact that I'm using the page's response status code which can be incorrect.

**Comment by Divide-By-0** [comment]
> > > @Divide-By-0 sorry, were there any issues that you wanted me to fix?
> > 
> > 
> > Hey sorry I haven't been as responsive. Just installed, will try out for a week. One quick nit is that the serif font is sort of ugly, and it should automatically check archive.org instead of asking me to click the button first.
> > Also, https://login.live.com/login.srf seems to trigger this extension even though it's not a 404.
> 
> I can definitely change the font style and make it check archive.org on initial load but I don't think I can do anything else to prevent false positives due to the fact that I'm using the page's response status code to detect a 404 page which can be incorrect.

From what I understand of that link, it gives a 404 then redirects automatically to a non-404, but your script doesn't seem to pick up the redirect.

**Comment by DanzHD** [comment]
> > > > @Divide-By-0 sorry, were there any issues that you wanted me to fix?
> > > 
> > > 
> > > Hey sorry I haven't been as responsive. Just installed, will try out for a week. One quick nit is that the serif font is sort of ugly, and it should automatically check archive.org instead of asking me to click the button first.
> > > Also, https://login.live.com/login.srf seems to trigger this extension even though it's not a 404.
> > 
> > 
> > I can definitely change the font style and make it check archive.org on initial load but I don't think I can do anything else to prevent false positives due to the fact that I'm using the page's response status code to detect a 404 page which can be incorrect.
> 
> From what I understand of that link, it gives a 404 then redirects automatically to a non-404, but your script doesn't seem to pick up the redirect.

Yep, you're right. I've uploaded a new update that should fix the issues and changes the font to Arial.

**Comment by Divide-By-0** [comment]
CNAME redirects still fail with your tool i.e. https://tool.zkregex.com/ or https://zkregex.com/tool.

**Comment by Divide-By-0** [comment]
Not sure Arial fits well with Chrome, can you try Segoe UI? Also can you make the button less tall?

**Comment by DanzHD** [comment]
> CNAME redirects still fail with your tool i.e. https://tool.zkregex.com/ or https://zkregex.com/tool.

Thanks for letting me know.

It seems that the final page from the redirect always sends back a 404 status code as the response. I checked with a redirect tool and it also gets a 404 status code back from the final page. Do you have any suggestions for potential fixes?

> Not sure Arial fits well with Chrome, can you try Segoe UI? Also can you make the button less tall?

Yep, I can do that.

**Comment by Divide-By-0** [comment]
> > CNAME redirects still fail with your tool i.e. https://tool.zkregex.com/ or https://zkregex.com/tool.
> 
> Thanks for letting me know.
> 
> It seems that the final page from the redirect always sends back a 404 status code as the response. I checked with a redirect tool and it also gets a 404 status code back from the final page. Do you have any suggestions for potential fixes?
> 
> > Not sure Arial fits well with Chrome, can you try Segoe UI? Also can you make the button less tall?
> 
> Yep, I can do that.

These don't 404 for me, can you figure out how to differentiate incorrect 404s from real 404s? It's a 404 on https but not on http I believe.

**Pull request closed without merging**
