### PR TITLE
Add nightcoreify

### PR DESCRIPTION
**Pull request by thomashuss**
**Automatically nightcore songs and post them as YouTube compilations**

I am not sure if my project matches what you had in mind with this description. I made it a while ago, before seeing this list :)

### CODE REVIEW

**Comment by Divide-By-0** [comment]
Cool! How do you avoid copyright strikes?

**Comment by thomashuss** [comment]
Believe it or not, copyright strikes have been the least of my worries.  I thought the channel would get struck down for copyright almost instantly, but it ended up receiving more strikes for suggestive content (from the images) than for copyright.  Most of the time, the videos don't get claimed for copyright; but when they do, it's rarely more severe than placing ads on the video (no problem since I don't monetize them) and blocking it in certain countries. I imagine the culture around music copyright has shifted in the past few years because of social media and streaming so I might be benefiting from that.

**Comment by Divide-By-0** [comment]
A few copyright strikes is my worry -- doesn't your youtube account get deleted after 3? My guess is that Content ID will start really screwing this idea once it hits thousands of views.

**Comment by thomashuss** [comment]
They expire after 90 days, and the last one was in October 2020, but you're right that this could be killed if it became more popular. I've considered limiting it to copyright free music, if I can find a way to identify such music either through YTAPI or scraping, but that would kill some of the novelty and humor value IMO.

In practice (at least right now), copyright hasn't been a big concern. In fact most videos are getting claimed due to audio fingerprinting -- here's a screenshot of the most recent uploads with a claim:
image

But this comfort could be due to the channel's relative obscurity.

**Comment by thomashuss** [comment]
My bad, I've fixed it now.

**Pull request closed without merging**
