### PR TITLE
Goodreads recommender

### PR DESCRIPTION
**Pull request by SamuelMoor-Smith**
Sorry I renamed the branch to make my forked repo cleaner

### CODE REVIEW

**Comment by SamuelMoor-Smith** [comment]
> Great start! I love the watchthis template! Makes the final book recommendations lay out look great. Some notes:

Link to the [goodreads export page](https://www.goodreads.com/review/import) on the website in the export section.
Where you say "Please select up to 10 books you would like to your recommendations to be similar to.", you should have enough context to be able to automatically put in the most polarized books first (i.e. 5s and 1s, then 2s and 4s, then 3s), with the shortest titles + author names first, and automatically prompt as many books as possible in the prompt, uptil the maximum prompt length. The user shouldn't have to auto select 10 books, it should all be automatic (but if you like that customizability, you can add an option for them to do that?)
Can you give credit to watchthis on the website somewhere? Maybe where it says powered by, add her repo/site? Her twitter/github is already there but maybe some explicit credit would be appreciated on her side.

fixing this now

**Comment by SamuelMoor-Smith** [comment]
I updated the repo and site to automatically add as many books to the prompt as possible. The books are sorted first by rating 5 > 1 > 4 > 2 > 3 then by existence of a review (if there is a review add it first). Lastly i sorted it so the shortest title + author is added first as you mentioned.

**Comment by SamuelMoor-Smith** [comment]
> I updated the repo and site to automatically add as many books to the prompt as possible. The books are sorted first by rating 5 > 1 > 4 > 2 > 3 then by existence of a review (if there is a review add it first). Lastly i sorted it so the shortest title + author is added first as you mentioned.

scratch that. having some problems with my tokenizer. will fix tomorrow.

**Comment by SamuelMoor-Smith** [comment]
It should be up and running now. I changed the tokenizer to https://www.npmjs.com/package/gpt-tokenizer so it could run in the browser. It seems to count tokens slightly differently than the official one (https://www.npmjs.com/package/gpt-3-encoder). I added a 100 token buffer to cure my paranoia but seems to work fine regardless.

**Comment by Divide-By-0** [comment]
How effective is the goodreads prompting? I imported my file and asked for recs but it just gave me the most popular books of all time (like catcher in the rye), which are nothing like my highly rated goodreads books.

**Comment by SamuelMoor-Smith** [comment]
> How effective is the new goodreads prompting? I imported my file and asked for recs but it just gave me the most popular books of all time (like catcher in the rye), which are nothing like my highly rated goodreads books.

You're right. Just ran a few tests and it seems its not great. I am upgrading the model to gpt-3.5-turbo now so hopefully that is better (probably should have used it in the first place).

**Comment by SamuelMoor-Smith** [comment]
Updated. The new model seems to give me much more niche results (which makes me think that it is using my Goodreads data more effectively). Let me know if you have the same experience :).

**Comment by Divide-By-0** [comment]
Looks better. One problem is that all of the books it recommends are from authors already in my list, vs I'd like to surface books/authors I haven't heard of yet as well. Let me know if its possible to tweak the prompt a bit to be more like that. 

Privately message me (at aayushg@mit.edu works) your preferred payment method for bounty payout (I like venmo or ethereum most, but can do paypal as well)!

**Comment by SamuelMoor-Smith** [comment]
> Looks better. One problem is that all of the books it recommends are from authors already in my list, vs I'd like to surface books/authors I haven't heard of yet as well. Let me know if its possible to tweak the prompt a bit to be more like that.
> 
> Privately message me (at [aayushg@mit.edu](mailto:aayushg@mit.edu) works) your preferred payment method for bounty payout (I like venmo or ethereum most, but can do paypal as well)!

I have updated the prompt to get some different authors. I also will send an email now.

**Pull request merged**
