### PR TITLE
Added Blink Tracker

### PR DESCRIPTION
**Pull request by djkovrik**
Liked the idea so here's my attempt 🙂 more or less matches to what you have in your specs document

### CODE REVIEW

**Comment by Divide-By-0** [comment]
Very awesome! Any chance you'd be able to add more than just today's data to the graph? Would be great to have some buttons saying like, 1m, 15m, 1h, 6h, 1d, 30d, 1y, etc; changing the time frame by which blinks per minute are averaged and graphed.

**Comment by djkovrik** [comment]
Sounds doable, I'll give it a try 👍🏻  Not sure about 1y though, for me 1m (or 30d like you mentioned) sounds like the best upper value

**Comment by djkovrik** [comment]
Pushed a new version with a few stats filters

**Comment by Divide-By-0** [comment]
The app works great, I just tried it. The minimized window is sort of intrusive, would be better to have a way that it runs in the background via a notification that shows blinks instead, let me know if you'd be down for that. In the current state I'm happy to pay the bounty though if recommend adding this, please email me your payment info! I prefer ethereum most. venmo second, PayPal is also ok.

**Comment by djkovrik** [comment]
@Divide-By-0 Thanks! Dropped a email a moment back 
As for minimized state, that's the only thing which I'm not 100% happy with rn 🙂 Already tried to customized Picture In Picture a bit but seems that it has some minimal size forced anyway and still looks kinda huge. So yeah notification was my next thought, prolly will make an additional option to replace PiP with it, gonna push another update somewhere during next week.

**Comment by djkovrik** [comment]
My other account is djk***gmail.com

**Comment by Divide-By-0** [comment]
Hey, there are some problems with low light and background persistence! @djkovrik any chance these can be fixed? https://github.com/djkovrik/BlinkTracker/issues/24

**Pull request merged**
