### PR TITLE
add sc-explorer contribution

### PR DESCRIPTION
**Pull request by k0dev**
sc-explorer is live!

### CODE REVIEW

**Comment by Divide-By-0** [comment]
I tried it with this link: https://m.soundcloud.com/discover/sets/charts-top:rbsoul:us

And it didn't work, it said I'd listened to everything.  Any idea why?

**Comment by k0dev** [comment]
> I tried it with this link: https://m.soundcloud.com/discover/sets/charts-top:rbsoul:us
> 
> And it didn't work, it said I'd listened to everything. Any idea why?

Because the soundcloud widget doesn't work with the top 50 playlist apparently :/
One workaround could be to translate a top 50 into a playlist on the fly

**Comment by k0dev** [comment]
> > I tried it with this link: https://m.soundcloud.com/discover/sets/charts-top:rbsoul:us
> > And it didn't work, it said I'd listened to everything. Any idea why?
> 
> Because the soundcloud widget doesn't work with the top 50 playlist apparently :/ One workaround could be to translate a top 50 into a playlist on the fly

Also if you notice, when you click share on a playlist on soundcloud web, there is an option to embed a player on a website. This option is not showed when you try to share a top 50 playlist. I think they are kind of "special" so the only solution could be to create a playlist on the fly! Or maybe we could pre-build some playlists as top 50 for all genres, and users could select one in alternative to providing a link to a playlist

**Comment by k0dev** [comment]
Done! Fixed in commit 24c4190

**Comment by Divide-By-0** [comment]
Do you mind editing the links to point to the latest version?

**Comment by k0dev** [comment]
Here you go :)

**Comment by Divide-By-0** [comment]
Awesome! Merging and paying now. It would still be nice to add https since my browser complains about the http security :P

**Comment by k0dev** [comment]
Will do!

**Pull request merged**
